'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '../lib/supabase';

const money = new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:2});

export default function Home(){
 const [supabase]=useState(()=>createClient()); const [session,setSession]=useState(null); const [rows,setRows]=useState([]); const [accounts,setAccounts]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [form,setForm]=useState({type:'expense',amount:'',category_name:'General',description:'',date:new Date().toISOString().slice(0,10),account_id:''});
 const load=async()=>{setLoading(true);setError(''); try{const {data:{session:s}}=await supabase.auth.getSession();setSession(s);if(!s){setLoading(false);return;} const [t,a]=await Promise.all([supabase.from('transactions').select('*').order('date',{ascending:false}).limit(100),supabase.from('accounts').select('*').order('name')]); if(t.error)throw t.error;if(a.error)throw a.error;setRows(t.data||[]);setAccounts(a.data||[]);}catch(e){setError(e.message||'Unable to load data')}finally{setLoading(false)}};
 useEffect(()=>{load(); const {data}=supabase.auth.onAuthStateChange(()=>load()); return()=>data.subscription.unsubscribe()},[]);
 const totals=useMemo(()=>rows.reduce((x,r)=>{const n=Number(r.amount)||0; r.type==='income'?x.income+=n:x.expense+=n;return x},{income:0,expense:0}),[rows]);
 const submit=async e=>{e.preventDefault();setError(''); if(!session)return; const amount=Number(form.amount);if(!amount||amount<0)return setError('Enter a valid amount'); const {error}=await supabase.from('transactions').insert({...form,amount,user_id:session.user.id,account_id:form.account_id||null});if(error)return setError(error.message);setForm({...form,amount:'',description:''});load()};
 const signIn=async()=>{const email=window.prompt('Email');if(!email)return;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});if(error)setError(error.message);else alert('Check your email for the login link.')};
 if(loading)return <main><div className="card">Loading Money Tracker…</div></main>;
 if(!session)return <main><div className="card"><h1>Money Tracker</h1><p className="muted">Secure BDT personal and business money management.</p><button className="btn" onClick={signIn}>Sign in with email</button>{error&&<p className="error">{error}</p>}</div></main>;
 return <main><div className="header"><div><h1>Money Tracker</h1><p className="muted">{session.user.email}</p></div><button className="btn secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div>
 <div className="grid" style={{marginTop:20}}><div className="card"><span className="muted">Income</span><div className="amount positive">{money.format(totals.income)}</div></div><div className="card"><span className="muted">Expense</span><div className="amount negative">{money.format(totals.expense)}</div></div><div className="card"><span className="muted">Net</span><div className={'amount '+(totals.income-totals.expense>=0?'positive':'negative')}>{money.format(totals.income-totals.expense)}</div></div><div className="card"><span className="muted">Accounts</span><div className="amount">{accounts.length}</div></div></div>
 <div className="card" style={{marginTop:20}}><h2>Add transaction</h2><form onSubmit={submit}><div className="toolbar"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option></select><input required type="number" min="0.01" step="0.01" placeholder="Amount BDT" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><input placeholder="Category" value={form.category_name} onChange={e=>setForm({...form,category_name:e.target.value})}/><select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="btn">Save</button></div></form>{error&&<div className="error">{error}</div>}</div>
 <div className="card" style={{marginTop:20}}><h2>Recent transactions</h2><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Date</th><th>Category</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.category_name}</td><td>{r.type}</td><td>{r.description}</td><td className={r.type==='income'?'positive':'negative'}>{money.format(Number(r.amount))}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="muted">No transactions yet.</td></tr>}</tbody></table></div></div>
 </main>
}
