'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '../lib/supabase';
const money=n=>new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:2}).format(Number(n)||0);
const incomeDefaults=['Salary','Business','Investment','Other Income'];
const expenseDefaults=['Food','Transport','Housing','Utilities','Education','Health','Shopping','Family','Other Expense'];
export default function Home(){
 const supabase=useMemo(()=>createClient(),[]),[session,setSession]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[accounts,setAccounts]=useState([]),[categories,setCategories]=useState([]),[transactions,setTransactions]=useState([]),[filter,setFilter]=useState('all'),[email,setEmail]=useState('');
 const [form,setForm]=useState({type:'expense',amount:'',category_name:'Food',date:new Date().toISOString().slice(0,10),description:'',method:'Cash',account_id:''});
 const load=async()=>{if(!session)return;setLoading(true);const [a,c,t]=await Promise.all([supabase.from('accounts').select('*').order('name'),supabase.from('categories').select('*').order('name'),supabase.from('transactions').select('*').order('date',{ascending:false}).limit(500)]);const e=a.error||c.error||t.error;if(e)setError(e.message);setAccounts(a.data||[]);setCategories(c.data||[]);setTransactions(t.data||[]);setLoading(false)};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[supabase]);useEffect(()=>{load()},[session]);
 const totals=transactions.reduce((x,r)=>{const n=Number(r.amount)||0;r.type==='income'?x.income+=n:x.expense+=n;return x},{income:0,expense:0});const balance=accounts.reduce((s,a)=>s+Number(a.balance||0),0);const visible=transactions.filter(t=>filter==='all'||t.type===filter);
 const signIn=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});if(error)setError(error.message);else alert('Login link sent. Check your email.')};
 const submit=async e=>{e.preventDefault();setSaving(true);setError('');const amount=Number(form.amount);if(!amount||amount<=0){setError('Amount must be greater than zero.');setSaving(false);return}const {error}=await supabase.from('transactions').insert({...form,amount,account_id:form.account_id||null,user_id:session.user.id});if(error)setError(error.message);else{setForm(f=>({...f,amount:'',description:''}));await load()}setSaving(false)};
 const addAccount=async()=>{const name=prompt('Account name');if(!name)return;const opening=Number(prompt('Opening balance','0')||0);const {error}=await supabase.from('accounts').insert({user_id:session.user.id,name,type:'cash',currency:'BDT',opening_balance:opening,balance:opening});if(error)setError(error.message);else load()};
 const remove=async id=>{if(!confirm('Delete transaction?'))return;const {error}=await supabase.from('transactions').delete().eq('id',id);if(error)setError(error.message);else load()};
 if(loading)return <main><div className="card"><h1>Money Tracker</h1><p>Loading…</p></div></main>;
 if(!session)return <main><section className="hero"><div><span className="eyebrow">PERSONAL FINANCE · BDT</span><h1>Money Tracker</h1><p>Secure income, expense and account management.</p></div><form className="card auth" onSubmit={signIn}><h2>Sign in</h2><input required type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn">Send login link</button>{error&&<p className="error">{error}</p>}</form></section></main>;
 const cats=categories.filter(c=>c.type===form.type).map(c=>c.name).concat(form.type==='income'?incomeDefaults:expenseDefaults).filter((v,i,a)=>a.indexOf(v)===i);
 return <main><header className="header"><div><span className="eyebrow">MONEY TRACKER</span><h1>Dashboard</h1><small>{session.user.email}</small></div><div className="actions"><button className="btn secondary" onClick={addAccount}>+ Account</button><button className="btn secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></header>
 <section className="stats"><div className="card"><span>Balance</span><strong>{money(balance)}</strong></div><div className="card"><span>Income</span><strong className="positive">{money(totals.income)}</strong></div><div className="card"><span>Expense</span><strong className="negative">{money(totals.expense)}</strong></div><div className="card"><span>Net</span><strong>{money(totals.income-totals.expense)}</strong></div></section>
 <section className="grid"><div className="card"><h2>Add transaction</h2><form className="form" onSubmit={submit}><div className="seg"><button type="button" className={form.type==='expense'?'selected':''} onClick={()=>setForm(f=>({...f,type:'expense',category_name:'Food'}))}>Expense</button><button type="button" className={form.type==='income'?'selected':''} onClick={()=>setForm(f=>({...f,type:'income',category_name:'Salary'}))}>Income</button></div><label>Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Category<select value={form.category_name} onChange={e=>setForm({...form,category_name:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>Account<select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">No account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {money(a.balance)}</option>)}</select></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Note<input value={form.description} placeholder="Optional" onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="btn" disabled={saving}>{saving?'Saving…':'Save transaction'}</button>{error&&<p className="error">{error}</p>}</form></div><div className="card"><div className="row"><h2>Accounts</h2><button onClick={addAccount}>Add</button></div>{accounts.length?accounts.map(a=><div className="account" key={a.id}><span><strong>{a.name}</strong><small>{a.type} · {a.currency}</small></span><strong>{money(a.balance)}</strong></div>):<p className="muted">No accounts yet.</p>}</div></section>
 <section className="card"><div className="row"><h2>Transactions</h2><div className="filters"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='income'?'selected':''} onClick={()=>setFilter('income')}>Income</button><button className={filter==='expense'?'selected':''} onClick={()=>setFilter('expense')}>Expenses</button></div></div><div className="table"><table><thead><tr><th>Date</th><th>Category</th><th>Type</th><th>Note</th><th>Amount</th><th></th></tr></thead><tbody>{visible.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.category_name}</td><td>{t.type}</td><td>{t.description}</td><td className={t.type==='income'?'positive':'negative'}>{t.type==='income'?'+':'−'}{money(t.amount)}</td><td><button className="delete" onClick={()=>remove(t.id)}>×</button></td></tr>)}</tbody></table>{!visible.length&&<p className="muted">No transactions.</p>}</div></section><footer>Money Tracker · Supabase RLS protected · BDT</footer></main>;
}
